import { Inter } from "next/font/google";
import "./globals.css";
import DataProvider from "./global/DataProvider";
import SocketProvider from "./userdashboard/global/SocketProvider";
import MessageProvider from "./userdashboard/global/messageProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default :'BCS preparation online platform',
    // template:'$s - BCS preparation online platform',
  },
   keywords : 'online bcs preparation, online job preparation, job prostuti, bcs prostuti, bcs help',
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <DataProvider>
           <SocketProvider>
              <MessageProvider>
                  <div className="max-w-[1440px] w-full mx-auto">{children}</div>
              </MessageProvider>
           </SocketProvider>
         </DataProvider>
        </body>
    </html>
  );
}
