import { Inter } from "next/font/google";
import "./globals.css";
import DataProvider from "./global/DataProvider";
import Head from "next/head";
import SocketProvider from "./userdashboard/global/SocketProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default :'BCS preparation online platform',
    // template:'$s - BCS preparation online platform'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7318908521952513"
      crossorigin="anonymous"></script>
      </Head>
      <body className={inter.className}>
         <DataProvider>
           <SocketProvider>
              <div className="max-w-[1440px] mx-auto">{children}</div>
           </SocketProvider>
         </DataProvider>
        </body>
    </html>
  );
}
