export const getHighlightedText = (text, highlight) => {
  const parts = text.split(new RegExp(`(${highlight})`, 'gi'));
  return parts.map((part, index) =>
    part.toLowerCase() === highlight.toLowerCase() ? (
      <strong key={index}>{part}</strong>
    ) : (
      <span key={index}>{part}</span>
    )
  );
};


export const ssc_dakhil_oLevel_cambridge_SSC_equivalent_hsc_alim_business_management =
  ["Business Studies", "General", "Humanities", "Science", "Other"];

export const ssc_vocational__dakhil_vocational = [
  "Agro-Based Food",
  "Architectural Drafting with CAD",
  "Automotive",
  "Building Maintenance",
  "Ceramic",
  "Civil Construction",
  "Civil Drafting with CAD",
  "Computer and Information Technology",
  "Dress Making",
  "Dyeing, Printing and Finishing",
  "Electrical Maintenance Works",
  "Farm Machinery",
  "Fish Culture and Breeding",
  "Food Processing and Preservation",
  "Fruit and Vegetable Cultivation",
  "General Electrical Works",
  "General Electronics",
  "General Mechanics",
  "Glass",
  "Knitting",
  "Livestock Rearing and Farming",
  "Machine Tools Operation",
  "Mechanical Drafting with CAD",
  "Patient Care Technique",
  "Plumbing and Pipe Fittings",
  "Poultry Rearing and Farming",
  "Refrigeration and Air Conditioning",
  "Shrimp Culture and Breeding",
  "Welding and Fabrication",
  "Wood Working",
  "Other",
];

export const diploma_in_engineering = [
  "Agriculture Technology",
  "Architecture and Interior Design Technology",
  "Automobile Technology",
  "Ceramic Technology",
  "Chemical Technology",
  "Civil Technology",
  "Computer Science & Engineering Technology",
  "Computer Science Technology",
  "Data Telecommunication and Network Technology",
  "Electrical and Electronics Technology",
  "Electrical Technology",
  "Electro-Medical Technology",
  "Electronics Technology",
  "Environmental Technology",
  "Firm Machinery",
  "Food",
  "Food Technology",
  "Garments Design and Pattern Making",
  "General Mechanics",
  "Glass Technology",
  "Graphic Design Technology",
  "Information and Communication Technology",
  "Instrumentation & Process Control Technology",
  "Jute Technology",
  "Library Science",
  "Marine Technology",
  "Mechanical Technology",
  "Mechatronics",
  "Mechatronics Technology",
  "Mining & Mine Survey Technology",
  "Power Technology",
  "Printing Technology",
  "Refrigeration & Air Conditioning Technology",
  "Shipbuilding Technology",
  "Survey",
  "Telecommunication Technology",
  "Textile Engineering",
  "Other",
];


export const diploma_in_medical_technology = [
    "Dental",
    "Laboratory",
    "Pharmacy",
    "Physiotherapy",
    "Radiography",
    "Radiotherapy",
    "Other"
  ];

  export const hsc_vocational = [
    "Agro Machinery",
    "Automobile",
    "Building Construction and Maintenance",
    "Clothing and Garments Finishing",
    "Computer Operation and Maintenance",
    "Drafting Civil",
    "Electrical Works and Maintenance",
    "Electronic Control and Communication",
    "Fish Culture and Breeding",
    "Industrial Wood Working",
    "Machine Tools Operation and Maintenance",
    "Poultry Rearing and Farming",
    "Refrigeration and Air-conditioning",
    "Welding and Fabrication"
  ];

  export const diploma_in_pharmachy = [
    "Dental",
    "Laboratory",
    "Pharmacy",
    "Physiotherapy",
    "Radiography",
    "Radiotherapy"
  ];



  ///////////////////////////////////////Honors////////////////////////////////////////
  export const bsc_engineering = [
    "Aeronautical Engineering",
    "Architecture",
    "Chemical Engineering",
    "Civil Engineering",
    "Computer Engineering",
    "Computer Science",
    "Computer Science & Engineering",
    "Computer Science & Information Technology",
    "Electrical & Electronics Engineering",
    "Electrical Engineering",
    "Electronic Engineering",
    "Electronics & Communication Engineering",
    "Electronics & Telecommunication Engineering",
    "Environmental Engineering",
    "Food and Process Engineering",
    "Genetic Engineering",
    "Glass and Ceramic Engineering",
    "Industrial Engineering",
    "Information and Communication Engineering",
    "Information and Communication Technology",
    "Leather Engineering",
    "Marine Engineering",
    "Materials Science & Engineering",
    "Mechanical Engineering",
    "Medical Physics and Biomedical Engineering",
    "Metallurgical Engineering",
    "Microwave Engineering",
    "Mineral Engineering",
    "Mining Engineering",
    "Naval Architecture & Marine Engineering",
    "Nuclear Engineering",
    "Petroleum & Mining Engineering",
    "Physical Planning",
    "Regional Planning",
    "Software Engineering",
    "Structural Engineering",
    "Telecommunication Engineering",
    "Textile Engineering",
    "Town Planning",
    "Urban & Regional Planning",
    "Water Resource Engineering",
    "Other"
  ];

  export const bsc_in_agricultural_science = [
    "Agr.Co-operative & Marketing",
    "Agriculture Chemistry",
    "Agriculture Co-operatives",
    "Agriculture Economics",
    "Agriculture Engineering",
    "Agriculture Extension",
    "Agriculture Finance",
    "Agriculture Marketing",
    "Agriculture Science",
    "Agriculture Soil Science",
    "Agriculture Statistics",
    "Agriculture Water Management",
    "Agro Forestry",
    "Agronnomy",
    "Agronomy & Aquaculture",
    "Agronomy & Aquaculture Extension",
    "Anatomology",
    "Anatomy & Histology",
    "Animal Breeding & Genetic",
    "Animal Husbandry",
    "Animal Nutrition",
    "Animal Science",
    "Bio-Technology",
    "Business Studies",
    "Corp Botany",
    "Dairy Science",
    "Doc.of Veterinary Science",
    "Farm Power & Machinery",
    "Farm Structure",
    "Fisheries",
    "Fisheries & Aquaculture",
    "Fisheries Biology",
    "Fisheries Management",
    "Fisheries Technology",
    "Food Tech. & Rural Industry",
    "Forestry",
    "Horticulture",
    "Livestock",
    "Microbiology & Hygenic",
    "Paratrology",
    "Plant Pathology",
    "Poultry Science",
    "Production Economics",
    "Rural Sociology",
    "Surgery & Obstate",
    "Other"
  ];


  export const mbbs_bds = [
    "Dental Surgery",
    "Medicine & Surgery",
    "Other"
  ];


 export const honors = [
    "Accounting",
    "Agriculture",
    "Anthropology",
    "Applied Chemistry",
    "Applied Mathematics",
    "Applied Physics",
    "Archaeology",
    "Bangla",
    "Banking",
    "Biochemistry",
    "Botany",
    "Business Administration",
    "Chemistry",
    "Clinical Psychology",
    "Communication Disorders",
    "Computer Engineering",
    "Computer Science",
    "Computer Science & Engineering",
    "Computer Science & Information Technology",
    "Criminology",
    "Criminology & Police Science",
    "Development Studies",
    "Disaster Science and Management",
    "Drama & Music",
    "Drawing and Printing",
    "Economics",
    "Education",
    "English",
    "Environmental science",
    "Ethics",
    "Finance",
    "Finance and Banking",
    "Fine Arts",
    "Folklore",
    "Food Technology and Nutrition Science",
    "Food Technology and Nutritional Science",
    "Forestry",
    "Genetic and Breeding",
    "Genetic Engineering and Biotechnology",
    "Geography",
    "Geography and Environmental Science",
    "Geology/Geology and Mining",
    "Government and Politics",
    "Graphics",
    "History",
    "History of Music",
    "Home Economics",
    "Industrial Arts",
    "Information and Communication Technology",
    "Information Science and Library Management",
    "Information Technology",
    "International Law",
    "International Relations",
    "Islamic History and Culture",
    "Islamic Studies",
    "Language/Linguistic",
    "Law/Jurisprudence",
    "Management",
    "Marine Science",
    "Marketing",
    "Mass Comm. & Journalism",
    "Materials Science & Engineering",
    "Mathematics",
    "Medical Technology",
    "Meteorology",
    "Microbiology",
    "Nutrition & Food Science",
    "Oceanography",
    "Pali",
    "Peace & Conflict",
    "Persian",
    "Pharmaceutical Chemistry",
    "Pharmacy",
    "Philosophy",
    "Physics",
    "Political Science",
    "Population Science",
    "Population Science and Human Resource Development (RU)",
    "Printing and Publication Studies",
    "Psychology",
    "Public Administration",
    "Public Finance",
    "Sanskrit",
    "Social Welfare/Social Work",
    "Social Works",
    "Sociology",
    "Soil Water and Environment Science",
    "Statistics",
    "Television, Film and Photography",
    "Urban Development",
    "Urdu",
    "Women and Gender Studies",
    "Women Studies",
    "World Religion",
    "Zoology",
    "Other"
  ];
  

  export const pass_course = [
    "B.A",
    "B.B.A",
    "B.B.S",
    "B.com",
    "B.S.S",
    "B.Sc",
    "L.L.B",
    "Other"
  ];

export const fazil = [
    "Akaid",
    "Arabic",
    "Fikha",
    "Hadith",
    "Islamic Studies",
    "Modern Arabic",
    "Tafsir",
    "Other"
  ];

 export const bba_course = [
    "Accounting",
    "Accounting and Information Systems",
    "Banking",
    "Banking and Insurance",
    "Business Administration",
    "Finance",
    "Finance and Banking",
    "Human Resource Management",
    "International Business",
    "Management",
    "Management Information Systems",
    "Marketing",
    "Organization Strategy and Leadership",
    "Tourism and Hospitality Management",
    "Other"
  ];
  
  
  